services:

  gymbro_db:
    image: postgres:15-alpine
    container_name: gymbro_db
    environment:
      POSTGRES_DB: Gymbro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MEp@706504
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Gymbro"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: gymbro-app
    ports:
      - "8080:8080"
    depends_on:
      gymbro_db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://gymbro_db:5432/Gymbro
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: MEp@706504
    restart: unless-stopped

volumes:
  postgres_data: