services:
  postgres:
    image: postgres:15-alpine
    container_name: gymbro_db
    environment:
      POSTGRES_DB: Gymbro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MEp@706504
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: gymbro-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped

volumes:
  postgres_data:
